name: Build and test

on: 
  push:
    master
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Build
      run: |
        yarn
        yarn build
    - name: Get default branch name
      run: echo ./dist/index.js ${{secrets.GITHUB_TOKEN}} "MindaugasLaganeckas/get-default-branch"
    - uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
    - uses: actions/upload-artifact@v2
      with:
        name: action.yml
        path: action.yml

  package:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    needs: [Build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Update distribution
          title: Update distribution
          body: |
            - Updates the distribution for changes on `master`
            Auto-generated by [create-pull-request][1]
            [1]: https://github.com/peter-evans/create-pull-request
          branch: update-distribution

